name: localpkg_flutter
description: "A new, object-oriented localpkg Flutter version."
version: 2.0.0
repository: https://github.com/Calebh101/localpkg-flutter-2
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  args: ^2.7.0
  http: ^1.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  readmore: ^3.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

  localpkg:
    git:
      url: https://github.com/Calebh101/localpkg-dart.git
      ref: 535bd4ead404823de81073086eeaa04b47018bbc

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
